import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Pastikan globals.css diimpor di sini

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Riko Maulana Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark"> {/* Saya tambahkan data-theme (DaisyUI) */}
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}